"""cleanup: drop legacy columns not in models

Revision ID: f28efde0d068
Revises: 89e8e5ca913a
Create Date: 2026-03-22 17:45:33.658179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28efde0d068'
down_revision: Union[str, Sequence[str], None] = '89e8e5ca913a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'razorpay_payout_id')
    op.alter_column('policies', 'subscription_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('policies', 'razorpay_subscription_id')
    op.alter_column('riders', 'subscription_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('riders', 'subscription_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('policies', sa.Column('razorpay_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('policies', 'subscription_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('claims', sa.Column('razorpay_payout_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
